# Generated by Django 4.2.1 on 2024-11-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('Theem', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark')], max_length=255, null=True, verbose_name='الثيم')),
                ('plan_type', models.CharField(choices=[('premium', 'Premium'), ('pro', 'PRO'), ('basic', 'Basic')], max_length=255, null=True, verbose_name='نو الاشتراك')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='السعر')),
                ('discont', models.IntegerField(default=0, null=True, verbose_name='خصم')),
                ('currency', models.CharField(choices=[('SAR', 'ريال سعودي'), ('USD', 'دولار'), ('EUR', 'يورو')], default='USD', max_length=250, null=True, verbose_name='العملة')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='هل الاشتراك مفعل ليظهر على الموقع')),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
    ]
