# Generated by Django 4.2.1 on 2024-11-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsmodel',
            name='plan_scope',
            field=models.CharField(choices=[('1', 'Monthly'), ('2', 'Yearly')], max_length=255, null=True, verbose_name='مدة الاشتراك'),
        ),
    ]
