# Generated by Django 4.2.1 on 2024-11-13 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100)),
                ('specialty_years_of_experience', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_state', models.CharField(choices=[('1', 'في قائمة الانتظار'), ('2', 'جاري التدقيق'), ('3', 'قبول'), ('4', 'رفض'), ('5', 'مستبعد')], default='1', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_img',
            new_name='profile_img_base64',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(choices=[('1', 'ابها'), ('2', 'ابو عريش'), ('3', 'احد المسارحة'), ('4', 'الأفلاج'), ('5', 'الاحساء'), ('6', 'الارطاوية'), ('7', 'الباحة'), ('8', 'البكيرية'), ('9', 'الثقبة'), ('10', 'الجبيل'), ('11', 'الخبر'), ('12', 'الخرج'), ('13', 'الخفجي'), ('14', 'الدلم'), ('15', 'الدمام'), ('16', 'الدوادمي'), ('17', 'الرس'), ('18', 'الرقعي'), ('19', 'الرياض'), ('20', 'الزلفي'), ('21', 'السليل'), ('22', 'الطائف'), ('23', 'العلا'), ('24', 'الغاط'), ('25', 'القريات'), ('26', 'القطيف'), ('27', 'القويعية'), ('28', 'المجمعه'), ('29', 'المدينة المنورة'), ('30', 'المذنب'), ('31', 'المزاحمية'), ('32', 'النعيرية'), ('33', 'النماص'), ('34', 'الهفوف'), ('35', 'املج'), ('36', 'بدر'), ('37', 'بريدة'), ('38', 'بقيق'), ('39', 'بلجرشي'), ('40', 'بيشة'), ('41', 'تبوك'), ('42', 'جازان'), ('43', 'جدة'), ('44', 'حائل'), ('45', 'حفر الباطن'), ('46', 'حقل'), ('47', 'حوطة سدير'), ('48', 'خميس مشيط'), ('49', 'خيبر'), ('50', 'دومة الجندل'), ('51', 'رابغ'), ('52', 'رياض الخبراء'), ('53', 'سبت العلايا'), ('54', 'سكاكا'), ('55', 'شرورة'), ('56', 'شقراء'), ('57', 'صبيا'), ('58', 'ضباء'), ('59', 'ضرما'), ('60', 'طريف'), ('61', 'عرعر'), ('62', 'عنيزة'), ('63', 'قرية العليا'), ('64', 'محايل عسير'), ('65', 'مكة المكرمة'), ('66', 'نجران'), ('67', 'وادي الدواسر'), ('68', 'ينبع')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('1', 'ذكر'), ('2', 'انثى')], default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='practitioner_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.practitionerprofilemodel'),
        ),
    ]
