# Generated by Django 4.2.1 on 2024-11-15 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_practitionerprofilemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الخدمة التي يقدمها صاحب المهنة.', max_length=100)),
                ('description', models.TextField(help_text='وصف شامل للخدمة يوضح تفاصيلها وما تقدمه.')),
                ('price', models.DecimalField(decimal_places=2, help_text='سعر الخدمة أو التكلفة المبدئية لها.', max_digits=10)),
                ('location', models.CharField(help_text='الموقع الجغرافي الذي تُقدم فيه الخدمة.', max_length=100)),
                ('category', models.CharField(help_text='الفئة العامة التي تندرج تحتها الخدمة.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='حالة الخدمة، سواء كانت متاحة أم لا.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='التاريخ والوقت الذي تمت فيه إضافة الخدمة.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='التاريخ والوقت الذي تم فيه آخر تعديل للخدمة.')),
                ('provider', models.ForeignKey(help_text='صاحب المهنة الذي يقدم الخدمة.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.servicemodel'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
