# Generated by Django 4.2.1 on 2024-11-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_servicemodel_alter_servicerequest_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='location',
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='duration',
            field=models.DurationField(help_text='المدة الزمنية المتوقعة لتقديم الخدمة.', null=True),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='img_base64',
            field=models.TextField(null=True),
        ),
    ]
