# Generated by Django 4.2.1 on 2024-11-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_servicemodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='duration',
            field=models.TextField(help_text='المدة الزمنية المتوقع لإكمال الخدمة.', null=True, verbose_name='المدة المتوقعة'),
        ),
    ]
