# Generated by Django 4.2.1 on 2024-11-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_servicemodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='duration',
            field=models.CharField(help_text='المدة الزمنية المتوقع لإكمال الخدمة.', max_length=50, null=True, verbose_name='المدة المتوقعة'),
        ),
    ]
