# Generated by Django 4.2.1 on 2024-11-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_servicemodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='location',
            field=models.CharField(help_text='الموقع الجغرافي الذي تُقدم فيه الخدمة.', max_length=100, null=True, verbose_name='الموقع'),
        ),
    ]
