# Generated by Django 4.2.16 on 2024-11-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_servicemodel_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='practitioner',
        ),
    ]
