# Generated by Django 4.2.16 on 2024-11-17 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_servicerequest_options_and_more'),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_messenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messenger.messengermodel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dont_receive_msg_from_companys',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dont_receive_msg_from_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_in_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_active_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'في انتظار الموافقة'), ('accepted', 'تم القبول الطلب'), ('rejected', 'تم الرفض الطلب'), ('completed', 'الطلب مكتمل')], default='pending', max_length=10),
        ),
    ]
