# Generated by Django 4.2.16 on 2024-12-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_active_messenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='geo_lat',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='geo_lng',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
