# Generated by Django 4.2.16 on 2024-11-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesmodel',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='messanger/audio/%Y/%m/%d/'),
        ),
    ]
