# Generated by Django 4.2.16 on 2024-11-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_messagesmodel_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmodel',
            name='msg',
            field=models.TextField(blank=True),
        ),
    ]
