# Generated by Django 4.2.16 on 2024-11-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_messagesmodel_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messanger/file/%Y/%m/%d/'),
        ),
    ]
