# Generated by Django 4.2.16 on 2024-12-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_messagesmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmodel',
            name='msg_type',
            field=models.CharField(choices=[('1', 'text'), ('2', 'file'), ('3', 'location'), ('4', 'audio')], max_length=50),
        ),
    ]
